# .github/FUNDING.yml
# Learn more: https://docs.github.com/sponsors/getting-started-with-github-sponsors

# GitHub Sponsors (recommended)
github: [jdmefsir]          # Your GitHub username (or org)

#Other platforms (uncomment the ones you use)
#patreon: jdmefsir           # Patreon username
#ko_fi: jdmefsir             # Ko-fi handle (no @)
#open_collective: jdmefsir   # Open Collective slug
#buy_me_a_coffee: jdmefsir   # Buy Me A Coffee username
#liberapay: jdmefsir         # Liberapay username

# One-time or external links (PayPal, Stripe, Gumroad, etc.)
#custom:
  # - https://paypal.me/jdmefsir
  # - https://ko-fi.com/jdmefsir
  # - https://buymeacoffee.com/jdmefsir
  # - https://stripe.com/pay/<your-link>
  # - https://opencollective.com/jdmefsir
